spring:
  datasource:
    username: shedlock
    password: pass
    url: jdbc:h2:mem:shedlock
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml